.PHONY: run-broker run-change-manager
run-broker:
	sudo PYTHONPATH=/home/pi/raspberry-pi/OnboardModules python3 /home/pi/raspberry-pi/OnboardModules/OnboardBroker/broker.py
run-change-manager:
	sudo PYTHONPATH=/home/pi/raspberry-pi/OnboardModules python3 /home/pi/raspberry-pi/OnboardModules/OnboardBroker/change_manager.py
